<!-- https://www.youtube.com/watch?v=zpkqNPwEzac&t=692s -->
<!-- https://towardsdatascience.com/slimming-down-your-docker-images-275f0ca9337e -->


Samller Container:
https://www.youtube.com/watch?v=CCFQFQ3vPfE


//
smaller Docker containers
https://www.youtube.com/watch?v=2KzDMD5Qk2k
https://www.youtube.com/watch?v=8vXoMqWgbQQ
https://www.youtube.com/watch?v=KLOdisHW8rQ